#!/bin/bash

# Get the current public IP of the instance
INSTANCE_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

# Jenkins config file location
JENKINS_CONFIG="/var/lib/jenkins/config.xml"

# Backup the original config file
cp $JENKINS_CONFIG ${JENKINS_CONFIG}.bak

# Update the Jenkins URL in the config file
sed -i "s|<jenkinsUrl>.*</jenkinsUrl>|<jenkinsUrl>http://${INSTANCE_IP}:8080/</jenkinsUrl>|g" $JENKINS_CONFIG

# Set proper permissions
chown jenkins:jenkins $JENKINS_CONFIG

# Restart Jenkins to apply changes
systemctl restart jenkins


sudo nano /etc/systemd/system/update-jenkins-url.service


[Unit]
Description=Update Jenkins URL with Public IP
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/bash /path/to/update-jenkins-url.sh
RemainAfterExit=true

[Install]
WantedBy=multi-user.target





sudo systemctl daemon-reload
sudo systemctl enable update-jenkins-url.service


sudo systemctl start update-jenkins-url.service


sudo usermod -aG myuser jenkins
